backend:
  name: git-gateway
  branch: main
collections:
  - name: sobre
    label: "Conteúdo página \"Sobre\""
    folder: static/sobre
    create: true
    extension: json
    fields:
      - {label: "História", name: "desc", widget: "markdown", required: true}
      - label: "Ficha"
        name: "ficha"
        widget: "list"
        allow_add: true
        required: true
        fields:
          - {label: Telefone, name: telefone, required: true, widget: "string"}
          - {label: "CRECI-BA", name: creciba, required: true, widget: "string"}
      - {label: "Foto", name: "photo", widget: "image", required: true}
  - name: propriedades
    label: Propriedades
    folder: static/propriedades
    create: true
    identifier_field: titulo
    extension: json
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      # Detalhes informativos
      - label: "Título"
        name: "titulo"
        widget: "string"
      - {label: "Descrição", name: "desc", widget: "markdown", required: true}
      - label: "Localização (em mapa)"
        name: "loc"
        widget: "map"
        default: "{ \"type\": \"Point\",\"coordinates\": [-40.8427477,-14.8519483]}"
      - label: "Salas"
        name: "salas"
        widget: "number"
        required: false
      - label: "Salas"
        name: "metros"
        widget: "number"
      - label: "Metros quadrados"
        name: "m2"
        widget: "float"
      # Galeria de imagens
      - label: "Fotos demonstrativas"
        name: "fotos"
        widget: "list"
        required: false
        allow_add: true
        fields: [{label: "Foto", name: "foto", widget: "image", choose_url: true, default: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=773&q=80", media_library: {config: {multiple: true}}}]
      # Youtube video
      - label: "Youtube video"
        name: "yt"
        widget: "string"
      # Se aplicável
      - {label: "Região", name: "regiao", widget: "string", required: false}
      - {label: "Água", name: "agua", widget: "boolean", required: false}
      - {label: "Luz", name: "luz", widget: "boolean", required: false}
      - {label: "Praça", name: "praca", widget: "boolean", required: false}
      - {label: "Condomínio", name: "condominio", widget: "boolean", required: false}
      - {label: "Asfaltamento", name: "asfaltamento", widget: "boolean", required: false}
        # Organização 
      - label: "Palavras-chave"
        name: "tags"
        widget: "list"
        allow_add: true
        add_to_top: true
        default: ["Novo"]

media_folder: "static/uploads"
public_folder: "/uploads"

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg